skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
q3_26_vault = "4HNnn4e5ttdSWco1euDyUXkrHu7GnPbyM2dpKvHheX2X"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
